fix amount in createOracleFeeData
sygmaprotocol/sygma-sdk pull request #162
Opened 2023-02-10 16:46 UTC by enemycnt

## Description

## Related Issue Or Context

Closes: #<issue>

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2023-02-10 16:48 UTC, wainola submitted a review, later dismissed

2023-02-13 13:44 UTC, mpetrun5 requested changes

2023-02-13 13:44 UTC, mpetrun5 commented on packages/sdk/src/fee/feeOracle.ts
> +    return oracleMessage + signature + toHex(amount, 32).substring(2);
Amount is currently number and will overflow when a large value is set.

2023-02-14 10:47 UTC, MakMuftic approved these changes

2023-02-14 10:47 UTC, mpetrun5 approved these changes

2023-02-14 10:48 UTC, merged