chore: fix root `package.json` and yarn
sygmaprotocol/sygma-sdk pull request #170
Opened 2023-02-16 19:17 UTC by BeroBurny

closes #168

2023-02-17 09:45 UTC, enemycnt requested changes
Please consider adding `.nvmrc` to `.gitignore`or rename to `.nvmrc.example`

2023-03-06 19:09 UTC, enemycnt approved these changes
I've updated `package.json` in examples to support modern version of yarn

2023-03-09 03:34 UTC, wainola submitted a review, later dismissed

2023-03-09 03:57 UTC, wainola approved these changes

2023-03-09 14:01 UTC, merged