Update deposit method to support substrate addresses
sygmaprotocol/sygma-sdk pull request #189
Opened 2023-03-08 22:16 UTC by enemycnt

Deposit and fee functions are updated to use addresses of variable size
SDK package type is rollbacked to commonjs. Module build will be enabled in #183 

## Description

## Related Issue Or Context

Closes: #186 

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2023-03-09 14:00 UTC, wainola requested changes
Fix eslint CI messages

2023-03-09 16:03 UTC, wainola submitted a review, later dismissed

2023-03-13 15:12 UTC, BeroBurny approved these changes

2023-03-13 16:07 UTC, wainola approved these changes

2023-03-13 16:08 UTC, merged