Extract or move current evm fee related functions to EVM folder
sygmaprotocol/sygma-sdk pull request #209
Opened 2023-03-24 20:22 UTC by enemycnt

## Description

## Related Issue Or Context

Closes: #195

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2023-03-28 03:56 UTC, wainola requested changes

2023-03-28 03:56 UTC, wainola commented on packages/sdk/.eslintrc.cjs
how this file works with the others in the others pull request?

2023-03-28 03:56 UTC, wainola commented on packages/sdk/src/chains/EVM/fee/basicFee.ts
> + * Calculates and returns the feeData object after query the FeeOracle service
Could you add the `@name` tag?

2023-03-28 03:56 UTC, wainola commented on packages/sdk/src/chains/EVM/fee/basicFee.ts
> +    console.error('Invalidad basic fee response');
Could we log the error anyways?

2023-03-28 03:56 UTC, wainola commented on packages/sdk/src/chains/EVM/fee/dynamicFee.ts
> + * Creates feeData structure with the following parameters.
Could you add the `@name` tag?

2023-03-28 03:56 UTC, wainola commented on packages/sdk/src/chains/EVM/fee/dynamicFee.ts
> + * Calculates the dynamic fee for a transaction using the provided parameters and the Fee Oracle.
Same as above

2023-03-28 03:56 UTC, wainola commented on packages/sdk/src/chains/EVM/fee/dynamicFee.ts
> + * Fetches oracle resource data from the FeeOracle service.
Same as above

2023-03-29 11:56 UTC, enemycnt commented on packages/sdk/.eslintrc.cjs
It works well for CI, the updated version for VScode will be merged with other PRs. I don't want to copy-paste it to every PR

2023-03-29 12:29 UTC, enemycnt commented on packages/sdk/src/chains/EVM/fee/basicFee.ts
> +    console.error('Invalidad basic fee response');
done

2023-03-31 11:58 UTC, MakMuftic approved these changes

2023-04-03 16:04 UTC, wainola approved these changes

2023-04-03 16:05 UTC, merged