Methods to set fee settings and general usage with shared config
sygmaprotocol/sygma-sdk pull request #212
Opened 2023-03-28 01:02 UTC by wainola

…s to work with usage of shared-config

## Description

## Related Issue Or Context

Closes: #<issue>

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2023-03-29 12:11 UTC, enemycnt submitted a review, later dismissed

2023-03-30 12:44 UTC, enemycnt requested changes

2023-03-30 12:44 UTC, enemycnt commented on packages/sdk/src/fee/feeHandler.ts
> +    return Promise.reject(new Error('Error fetching fee handler address'));
To propagate error:
```suggestion
    return Promise.reject(error);
```

2023-03-30 12:44 UTC, enemycnt commented on packages/sdk/src/fee/feeHandler.ts
> +): Promise<string | Error> => {
It is connected with next comment
```suggestion
): Promise<string> => {
```

2023-03-30 14:23 UTC, MakMuftic commented on packages/sdk/src/Sygma.ts
> +  public getFeeRouterAddress(chain: 'chain1' | 'chain2'): string {
There is a type for `chain1' | 'chain2'`, called [`Directions`](https://github.com/sygmaprotocol/sygma-sdk/blob/47df66e41314cd225165fabe50167f96ca80c8b5/packages/sdk/src/types/types.ts#L8). 

Even though I am not sure if that is the best name for this type, let us use the defined type everywhere - it is easy to rename it in the future.

2023-03-30 14:41 UTC, MakMuftic approved these changes

2023-03-30 14:44 UTC, enemycnt approved these changes

2023-03-30 14:44 UTC, merged