feat: parachain support
sygmaprotocol/sygma-sdk pull request #289
Opened 2023-07-26 11:00 UTC by mpetrun5

Add support for providing parachain ID to target parachains other than Phala/Khala.

## Description

## Related Issue Or Context

Closes: #288 

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [x] I have updated the documentation locally and in chainbridge-docs.
- [x] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2023-07-31 01:56 UTC, wainola submitted a review, later dismissed

2023-07-31 13:58 UTC, MakMuftic requested changes

2023-07-31 13:58 UTC, MakMuftic commented on packages/sdk/src/chains/EVM/helpers.ts
> +            parachain: 2006,
Why is this hardcoded to 2006?

2023-07-31 14:40 UTC, MakMuftic submitted a review, later dismissed

2023-08-02 07:54 UTC, MakMuftic approved these changes

2023-08-02 08:17 UTC, tcar121293 approved these changes

2023-08-02 08:46 UTC, merged