feat: Add routes and domains helper functions
sygmaprotocol/sygma-sdk pull request #340
Opened 2024-02-12 11:38 UTC by MakMuftic

## Description

## Related Issue Or Context

Closes: #<issue>

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2024-02-12 12:00 UTC, mpetrunic requested changes

2024-02-12 13:16 UTC, mpetrunic commented on packages/sdk/src/utils.ts
> +  sourceChainId: number,
nvm found hack

2024-02-12 15:38 UTC, mpetrunic commented on packages/sdk/src/types/types.ts
> +  // domainID -> DomainMetadata
does it also work for resourceId?

2024-02-13 10:00 UTC, mpetrunic reviewed
You should probably open issue to use this in SDK, as right now if route is unsupported this is error from SDK:
![image](https://github.com/sygmaprotocol/sygma-sdk/assets/8836210/b5b42836-a727-4d99-8122-3b7a4e4c653b)

😅

2024-02-14 08:11 UTC, mpetrunic submitted a review, later dismissed

2024-02-14 09:31 UTC, MakMuftic commented
## New updates
- removed `axios` as dependency
  - we were using both axios and fetch in codebase, so refactored it to use fetch
- added `isTransferValid` function to BaseAssetTransfer

2024-02-14 09:33 UTC, MakMuftic commented on packages/sdk/src/types/types.ts
> +  // domainID -> DomainMetadata
This will be a separate PR

2024-02-14 09:49 UTC, mpetrunic approved these changes

2024-02-14 09:49 UTC, mpetrunic commented on packages/sdk/package.json
> +    "cross-fetch": "^4.0.0",
https://github.com/sygmaprotocol/sygma-sdk/issues/344 😛

2024-02-14 10:13 UTC, mpetrunic approved these changes

2024-02-14 13:12 UTC, wainola approved these changes

2024-02-14 13:37 UTC, merged